sudo: required

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers
    - $HOME/build

services:
  - docker

before_install:
  - sbt package
  - sbt assembly
  - docker network create platform
  - docker-compose up -d
  - docker-compose ps
  - sbt scalastyle
