version: '2'

services:
  master:
    image: 'gettyimages/spark'
    command: bin/spark-submit /shock/scala-2.11/shock_2.11-0.0.1.jar -h 172.17.0.1
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
      - ./target:/shock

networks:
  default:
    external:
      name: platform
